---
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: git-credentials
  namespace: flux-system
spec:
  secretStoreRef:
    name: demo-css
    kind: ClusterSecretStore
  refreshInterval: "60s"
  data:
    - remoteRef:
        key: kv/flux/service-account
        property: private.key
      secretKey: identity
    - remoteRef:
        key: kv/flux/service-account
        property: passphrase
      secretKey: password
    - remoteRef:
        key: kv/flux/service-account
        property: public.key
      secretKey: known_hosts
